# Generated by Django 5.1.4 on 2025-04-18 02:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('supplier', '0003_remove_supplier_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonType',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Actualizado por')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_input', models.BooleanField(default=True, verbose_name='Es Entrada')),
            ],
            options={
                'verbose_name': 'Tipo de Movimiento',
                'verbose_name_plural': 'Tipos de Movimientos',
                'db_table': 'movement_type',
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Actualizado por')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('direction', models.CharField(choices=[('input', 'Entrada'), ('output', 'Salida')], max_length=10, verbose_name='Dirección del Movimiento')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Total')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('final_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='product.finalproduct', verbose_name='Producto Final')),
                ('primary_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='product.primaryproduct', verbose_name='Producto Primario')),
                ('product_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='product.productcolor', verbose_name='Color del Producto')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_movements', to='supplier.supplier', verbose_name='Proveedor')),
                ('movement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='movement.reasontype', verbose_name='Motivo del Movimiento')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'inventory_movement',
            },
        ),
    ]
