# Generated by Django 5.1.4 on 2025-04-18 03:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0001_initial'),
        ('product', '0001_initial'),
        ('supplier', '0003_remove_supplier_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorymovement',
            old_name='movement_type',
            new_name='reason_type',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='final_product',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='primary_product',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='product_color',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='inventorymovement',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='direction',
            field=models.CharField(choices=[('input', 'Entrada'), ('output', 'Salida')], max_length=10, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplier', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='InventoryMovementDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='Precio Total')),
                ('final_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.finalproduct', verbose_name='Producto Final')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='movement.inventorymovement', verbose_name='Movimiento')),
                ('primary_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.primaryproduct', verbose_name='Producto Primario')),
                ('product_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcolor', verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Detalle del Movimiento',
                'verbose_name_plural': 'Detalles de Movimiento',
                'db_table': 'inventory_movement_detail',
            },
        ),
    ]
