# Generated by Django 5.1.4 on 2025-04-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0002_rename_movement_type_inventorymovement_reason_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymovement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reasontype',
            name='is_input',
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Cliente'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Precio Total'),
            preserve_default=False,
        ),
    ]
