# Generated by Django 5.1.4 on 2025-04-29 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0003_remove_inventorymovement_date_and_more'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymovementdetail',
            options={'verbose_name': 'Detalle de Movimiento de Inventario', 'verbose_name_plural': 'Detalles de Movimientos de Inventario'},
        ),
        migrations.AlterField(
            model_name='inventorymovementdetail',
            name='final_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.finalproduct'),
        ),
        migrations.AlterField(
            model_name='inventorymovementdetail',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='movement.inventorymovement'),
        ),
        migrations.AlterField(
            model_name='inventorymovementdetail',
            name='primary_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.primaryproduct'),
        ),
        migrations.AlterField(
            model_name='inventorymovementdetail',
            name='product_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productcolor'),
        ),
        migrations.AlterField(
            model_name='inventorymovementdetail',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorymovementdetail',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventorymovementdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
