# Generated by Django 5.1.4 on 2025-06-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movement', '0004_alter_inventorymovementdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='direction',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=10, verbose_name='Dirección'),
        ),
    ]
