# Generated by Django 5.1.4 on 2025-04-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='primary_product',
            field=models.ManyToManyField(related_name='suppliers', to='product.primaryproduct'),
        ),
        migrations.DeleteModel(
            name='ProductSupplier',
        ),
    ]
