# Generated by Django 5.1.4 on 2025-04-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplier_primary_product_delete_productsupplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='name',
        ),
    ]
