# Generated by Django 5.1.4 on 2025-04-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_remove_supplier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RUC'),
        ),
    ]
